### PR TITLE
Add required API version declaration in plugin.yml

### PR DESCRIPTION
**Pull request by jchoyt**
Reduces errors when started on spigot

### CODE REVIEW

**Comment by KisaragiEffective** [comment]
@jchoyt not `1.6` but `1.16`

**Comment by RobinWhitfield** [comment]
I wonder what issues came up that caused this reversion:
https://github.com/webbukkit/dynmap/commit/178681d28413aa49d42100bf689b5f889a528409

**Comment by mikeprimm** [comment]
This is broken

**Comment by mikeprimm** [comment]
The api-version change breaks any Spigot version older than the version you put in, and Dynmap supports versions back to before 1.10 with the same binary.

**Pull request closed without merging**
