### PR TITLE
Hikari CP implementation

### PR DESCRIPTION
**Pull request by ishland**
Using HikariCP to improve performance of SQL and other databases.

Tests are performed on Paper 1.15.2

- [x]  Implement HikariCP for MySQL

- [x] Implement HikariCP for MariaDB

- [x] Implement HikariCP for PostgreSQL

- [x] Implement HikariCP for SQLite

- [x] Change everything to PreparedStatements

- [ ] Testing

  - [x] MySQL testing

  - [x] MariaDB testing

  - [ ] PostgreDB testing

  - [ ] SQLite testing

### CODE REVIEW

**Comment by ishland** [comment]
Everything is ready except for testing
PostgreSQL left untested

**Comment by ishland** [comment]
Updated to 10529e1

**Comment by ishland** [comment]
Updated to dfbe83f57c1da0b3c9df339311f227bddc72c728

**Comment by baconwaifu** [comment]
I would recommend splitting this into multiple pull requests, that would make it more likely that some or all changes get accepted, compared to a monolithic pull.

I see a couple distinct changes here:
- An overhaul of my postgres driver.
- Merging of two near-identical db drivers
- Formatting fixups
- Consistent Prepared Statements
- SQL server pool support via "HikariCP"

Splitting the formatting off and getting that merged quickly would also prevent needing to manually merge every update to master, as that's by far the most invasive change.

**Review by ice-fly — APPROVED** [review]

**Comment by mikeprimm** [comment]
@baconwaifu is correct - besides the merge conflicts, I don't generally accept really big changes, and I almost never accept big 'formatting'/prettying-up changes, as they are too hard to review and don't accomplish anything.   I need PRs to be focused and minimal in order to reasonably review and accept them, as there are often things I might accept (a new DB driver support) mixed with things I will not accept (wide scale restyling of core modules with no resulting functional benefit).

**Pull request closed without merging**
