### PR TITLE
update tiles storage to use mediumblob

### PR DESCRIPTION
**Pull request by JurgenKuyper**
set type to mediumblob to allow for boost type 3 to be stored

### CODE REVIEW

**Review by mikeprimm — APPROVED** [review]

**Comment by mikeprimm** [comment]
Looks good - trying to decide if we should do an ALTER to handle existing DBs

**Comment by molor** [comment]
So existing DBs will be updated automatically?

**Comment by molor** [comment]
Excellent support :/

_note_: `sarcasm`

**Comment by JurgenKuyper** [comment]
> Looks good - trying to decide if we should do an ALTER to handle existing DBs

That might be good as it shouldn't make a difference for the user

**Pull request merged**
