### PR TITLE
Fabric support (1.16.1 and 1.16.2)

### PR DESCRIPTION
**Pull request by lhns**
See https://github.com/webbukkit/dynmap/issues/2697#issuecomment-673095879 for previous discussion.
Until this is merged you can get the unofficial version here: https://github.com/LolHens/dynmap-fabric

I have already integrated the two new submodules into the build process. Maybe the artifact paths need to be changed.
Also there are ~~3~~ 2 new TODOs in the code (see second and third commit) which should probably be adressed in the future but for now they have workarounds and they don't seem to break anything.
~~EDIT: there seems to be a bug which causes chunks to look corrupted. We probably want to wait for that to be fixed first.
https://github.com/LolHens/dynmap-fabric/issues/19~~
~~EDIT: implemented a new workaround that doesn't seem to have said issues.~~
~~EDIT: just saw #3083. That's the same issue we are having on the fabric version. The fabric version just skips the chunk and therefore doesn't crash...~~
EDIT: fixed properly

@mikeprimm should I target master with this PR or do you want to create a fabric branch so you can tinker with this and change stuff before merging it into master?

### CODE REVIEW

**Comment by mikeprimm** [comment]
v3.0 is the right branch - this looks good.  My main thing is that I need for anyone who does PRs and the like on Dynmap - particularly anything that touches DynmapCore or DynmapCoreAPI - to build (and hopefully test, but at least build) their chances on EVERYTHING.  Back when the components were separate repos, I cannot tell you how often PRs were OK for just one platform, and broke everything else.... big reason we're not going back to anything that is a separate branch or repo, and why I'll probably do some work to get this stitched into a single build step (even if that is just a top level script that runs 'gradle' twice :)

**Comment by lhns** [comment]
That should already be that way. I integrated the two new platforms into the main gradle project.

**Comment by mikeprimm** [comment]
Perfect - looking forward to spending some time reviewing it after I release tonight, and we'll get things integrated!

**Review by mikeprimm — APPROVED** [review]

**Comment by mikeprimm** [comment]
This looks really good - I've merged it, and will be putting in some time to make sure that building and such by my process works as it should, and that the resulting artifacts are useful.  I'll kick a post here with links to the resulting builds - I'd very much appreciate some 'sanity checking' of these merged and formally built SNAPSHOT builds by any of the folks that have already been working with the unofficial builds.

**Pull request merged**
