### PR TITLE
Update NMS helpers failing to bind in 1.13

### PR DESCRIPTION
**Pull request by NathanWolf**
I started some preliminary work on updating dynmap to support 1.13.

I quickly ran into the realization that the renderer is heavily reliant on block ids, and that this was a much bigger problem than I was prepared to solve.

I hope you find time to work on this at some point, I'd love to see an updated dynmap one day. If you do, this PR may save you a little bit of time.

### CODE REVIEW

**Comment by mikeprimm** [comment]
Thanks for the PR, but I'm really gutting things pretty hard right now, and I've got this territory already covered :)

If you are interested in tracking the 1.13 work, and even helping, check out the 'v3.0-1.13_prep' branches of the dynmap, dynmap-api, DynmapCore, and DynmapCoreAPI repos.  These are now buildable and runnable on 1.13, and even MOSTLY working - definitely at a point where testing and some additional dev-grade input would be welcome!

**Comment by mikeprimm** [comment]
My current 'bleeding edge' build is at http://dynmap.us/builds/dynmap-1.13_prep/dynmap-3.0-1.13_prep-HEAD.jar (spigot only right now, although this build should work with anything after Spigot 1.8.8 or so).

**Comment by NathanWolf** [comment]
Awesome, thanks! I'll put this on my dev server, if I see any issues I'll try to help.

**Comment by NathanWolf** [comment]
Do you think I would need to redo my configs?

I'm guessing you don't want me opening issues for this branch, though this probably isn't the best place either I just thought I'd share my initial experience.

- It worked fine on a local server with fresh configs
- I dropped it on my dev server, which has some slightly-tweaked but maybe-ancient configs and got mixed results

I tried to render an area outside my spawn where I had copied a 1.13 ocean:

1.13 area

It came out like this (radius render in-progress)

rendered

larger area:
larger

at first I thought it was just mis-handling the new water, but it seems like a bigger issue than that. The map is here:

http://map.elmakers.com/?worldname=world&mapname=surface_se&zoom=5&x=-13580&y=64&z=6624

Though I may disable it if I can't figure it out so I get map corruption. I'll leave notes here if I figured anything out.

Thank you!

**Comment by NathanWolf** [comment]
Minor update: I was wrong about my local server, it looks like it's also broken in a similar way. It basically looks like only a few basic block types are rendering and the rest are invisible.

I tried copying the 1.13 vanilla RP to texturepacks/standard, zipped and unzipped, but didn't help. I do get a few errors, mostly this:
```
[07:48:16 INFO]: [dynmap] Loading default resource pack
[07:48:16 WARN]: [dynmap] Resource assets/minecraft/textures/block/dirt_podzol_top.png for mod minecraft not found
[07:48:16 WARN]: [dynmap] Resource assets/minecraft/textures/block/dirt_podzol_side.png for mod minecraft not found
[07:48:16 WARN]: [dynmap] Resource assets/minecraft/textures/block/stone_granite.png for mod minecraft not found
[07:48:16 WARN]: [dynmap] Resource assets/minecraft/textures/block/stone_granite_smooth.png for mod minecraft not found
[07:48:16 WARN]: [dynmap] Resource assets/minecraft/textures/block/stone_diorite.png for mod minecraft not found
[07:48:16 WARN]: [dynmap] Resource assets/minecraft/textures/block/stone_diorite_smooth.png for mod minecraft not found
[07:48:16 WARN]: [dynmap] Resource assets/minecraft/textures/block/stone_andesite.png for mod minecraft not found
[07:48:16 WARN]: [dynmap] Resource assets/minecraft/textures/block/stone_andesite_smooth.png for mod minecraft not found
```

```

[07:47:32 ERROR]: [dynmap] Invalid rotate ID: minecraft:bed on line 413
[07:47:32 ERROR]: [dynmap] Format error - line 565 of texture_1.txt: Unknown attribute: dark_oak_sapling
[07:47:32 ERROR]: [dynmap] Block minecraft:fire[age=0,east=true,north=true,south=true,up=true,west=true] - not enough textures for faces (7 > 6)
```

This may be out of the realm of anything I can help with, sorry! Please keep me updated if you can :)

**Comment by smmmadden** [comment]
I've just downloaded the jar for my test servers 1.13 and 1.12.2 and will provide results as requested once I get the maps generated and can walk through each of the features in more granular detail for both releases.  Thanks Mike, this is a huge step forward for everyone. :-)

**Comment by smmmadden** [comment]
New Spigot 1.13 world with WorldBorder 1.8.7 on Spigot.  Made zero changes to default configuration to render as a new world would do (deftemplatesuffix: hires).  Integration between the 1.12.2 version of WB and Dynmap looks good for flat and surface maps, but cave map shows double border (inner in red, outer in blue).  Set the border and ran the wb fill command.  I saw in the startup logs/console it identifying the new block names and saw the 16 entries for water.  So I guess this might be one to wait for?
[11:46:10] [Server thread/INFO]: [dynmap] 34: blk=minecraft:water, idx=0, state=level=0
[11:46:10] [Server thread/INFO]: [dynmap] 35: blk=minecraft:water, idx=1, state=level=1
[11:46:10] [Server thread/INFO]: [dynmap] 36: blk=minecraft:water, idx=2, state=level=2
[11:46:10] [Server thread/INFO]: [dynmap] 37: blk=minecraft:water, idx=3, state=level=3
[11:46:10] [Server thread/INFO]: [dynmap] 38: blk=minecraft:water, idx=4, state=level=4
[11:46:10] [Server thread/INFO]: [dynmap] 39: blk=minecraft:water, idx=5, state=level=5
[11:46:10] [Server thread/INFO]: [dynmap] 40: blk=minecraft:water, idx=6, state=level=6
[11:46:10] [Server thread/INFO]: [dynmap] 41: blk=minecraft:water, idx=7, state=level=7
[11:46:10] [Server thread/INFO]: [dynmap] 42: blk=minecraft:water, idx=8, state=level=8
[11:46:10] [Server thread/INFO]: [dynmap] 43: blk=minecraft:water, idx=9, state=level=9
[11:46:10] [Server thread/INFO]: [dynmap] 44: blk=minecraft:water, idx=10, state=level=10
[11:46:10] [Server thread/INFO]: [dynmap] 45: blk=minecraft:water, idx=11, state=level=11
[11:46:10] [Server thread/INFO]: [dynmap] 46: blk=minecraft:water, idx=12, state=level=12
[11:46:10] [Server thread/INFO]: [dynmap] 47: blk=minecraft:water, idx=13, state=level=13
[11:46:10] [Server thread/INFO]: [dynmap] 48: blk=minecraft:water, idx=14, state=level=14
[11:46:10] [Server thread/INFO]: [dynmap] 49: blk=minecraft:water, idx=15, state=level=15
image
Then followed up with /dynmap fullrender world to see if the generated water blocks are updated and didn't see any changes to the map for flat or surface.  Continuing testing other features...

**Comment by NathanWolf** [comment]
Seems like you are having better luck than I! Have you tried an isometric map?

**Comment by smmmadden** [comment]
not yet, just got done testing the skins for face and full body and that looks good.  Still waiting on fullgeneration to complete and then I'll be testing the different map resolutions and other features in the configuration.txt file.

**Comment by fichdlmaa** [comment]
**Successfull fullrender on Spigot-1-13 Jenkins build 1782 (2018-08-12) +++**
DynMap runs stable and without errors. No conflict with Redprotect, CMI, a.s.o.

Very awesome results - Have a look at the attached Screenshots - Thank you very much!:

[14:36:14 INFO]: [dynmap] Loading dynmap v3.0-SNAPSHOT-24
[14:36:14 INFO]: [dynmap] version=git-Spigot-2b0e71c-c0df4b8 (MC: 1.13)
[14:36:14 INFO]: [dynmap] Unload queue not found - default to unload all chunks
[14:36:14 INFO]: [dynmap] Mod Support API available
...
[14:39:30 INFO]: [dynmap] Loading default resource pack
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/dispenser_front_horizontal.png for mod minecraft not found
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/sandstone_carved.png for mod minecraft not found
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/sandstone_normal.png for mod minecraft not found
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/sandstone_smooth.png for mod minecraft not found
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/noteblock.png for mod minecraft not found
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/rail_golden_powered.png for mod minecraft not found
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/rail_golden.png for mod minecraft not found
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/rail_detector.png for mod minecraft not found
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/log_acacia.png for mod minecraft not found
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/log_acacia_top.png for mod minecraft not found
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/stripped_log_acacia.png for mod minecraft not found
[14:39:30 WARN]: [dynmap] Resource assets/minecraft/textures/block/stripped_log_acacia_top.png for mod minecraft not found
[14:39:57 INFO]: FichdlMaa issued server command: /dynmap fullrender

...
>version
[16:18:43 INFO]: This server is running CraftBukkit version git-Spigot-2b0e71c-c0df4b8 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Greets FichdlMaa


bildschirmfoto - 12 08 2018 - 15 34 45
bildschirmfoto - 12 08 2018 - 16 06 58
bildschirmfoto - 12 08 2018 - 16 05 36
bildschirmfoto - 12 08 2018 - 16 02 15
bildschirmfoto - 12 08 2018 - 16 00 24

**Comment by NathanWolf** [comment]
Wow those look great! Well @mikeprimm sorry for the tag but if you ever get a spare moment I'd be really curious to know what I've done wrong. I have tried with completely fresh configs...

@fichdlmaa did you have to do anything special to make dynmap know about the 1.13 RP- is this running on a remote server, did you upload the RP to it or anything?

**Comment by fichdlmaa** [comment]
@NathanWolf 
Nothing special. Only loaded the latest DynMap dev and RP dev; afterwards (re)run (old Jenkins 25) buildtools for 1.13. I only created a little test zone some weeks ago.

Today we made little LAN party on this local test server. nor errors neither warnings on server console +++
The RedProtect zone is displayed correctly (when layer is activated ;-) )

**Comment by NathanWolf** [comment]
Sorry, what do you by "RP dev"? Is that a plugin or did you mean resource pack?

**Comment by fichdlmaa** [comment]
Ah. Misunderstood: RP = RedProtect; dev = develeopment build
DynMap is NOT a ressource pack, it's a plugin!

**Comment by NathanWolf** [comment]
Ah ok, sorry no clue what RedProtect is but I assume its unrelated :)

I was trying to figure out if you put the vanilla 1.13 resource pack in dynmap's resourcepacks folder or something similar. I can't figure out why it's not rendering properly for me.

**Pull request closed without merging**
