### PR TITLE
implemented catch to prevent server crash when jar in jar methods are used

### PR DESCRIPTION
**Pull request by JurgenKuyper**
Forge added the option to nest Jar files, which dynmap doesn't support, added a patch so the server no longer crashes when this is the issue, a full implementation to read the data from the nested jars needs to be implemented but I couldn't get it to work.

### CODE REVIEW

**Comment by kosma** [comment]
FWIW, I've had the same problem when trying to do JiJ on Fabric. There's gotta be a way to fix this...

**Comment by JurgenKuyper** [comment]
I left my tried final code in comments to fix it, just couldn't get the proper jar:// path out of it, it kept returning the input jarID for some reason, have been trying for a while and decided to just patch and deploy it.

**Comment by BartDotRun** [comment]
Is there any workaround for now?

**Comment by JurgenKuyper** [comment]
Building the jar yourself is the workaround, from my repo

**Comment by mikeprimm** [comment]
I see what was done here, but am unclear as to when the files being fetched would involve jar-in-jar resolution - can I get a specific case where this is so?

**Pull request merged**
