### PR TITLE
Colorful biomes

### PR DESCRIPTION
**Pull request by masmc05**
Adds support for 
image
1. support for datapack colors for grass and foliage
2. support for biome grass color modifiers like darker dark forest's color or changeable swamp's color (so supress https://github.com/webbukkit/dynmap/pull/3832 since it adds same effects automatically)

Also add colors for missing biomes (like badlands)
Before:
image
After:
image

### CODE REVIEW

**Comment by masmc05** [comment]
[world.zip](https://github.com/webbukkit/dynmap/files/9785818/world.zip)
the world from screenshot if someone wants to make tests and don't want to search for biomes with custom colors (in vanilla format, but bukkit can transform to bukkit format)

**Comment by masmc05** [comment]
Added support for even 1.16.5 and 1.16.4, but don't like the reflection so won't add for 1.16.2 and 1.16.3, most users won't notice that anyway since they'll use latest 1.16.* already

**Comment by masmc05** [comment]
Tested and works on every version on every platform
if you're ok to download a jar from stranger you can get compiled verion [here](https://drive.google.com/drive/folders/1TRWYzfriwW-oDqKAVM0Q3DKo4fvVmjD9?usp=sharing), but i recommend compiling yourself

**Comment by mikeprimm** [comment]
Looks good - thanks!

**Pull request merged**
