### PR TITLE
Update LuckPerms and bStats

### LINKED ISSUE #2643: Cannot build due to retired repo from bstats
I got 522 for few dependecy and I cannot build dynmap I asked bstats from github they said that repo is retired.

https://github.com/Bastian/bStats/issues/106

### LINKED ISSUE #2665: Incompatibility with LuckPerms v5 API
dynmap beta-6-220
LuckPerms 5.0.3 dev 925

```
[02:01:30] [Server thread/INFO]: [dynmap] Enabling dynmap v3.0-beta-6-220*
[02:01:30] [Server thread/ERROR]: Error occurred while enabling dynmap v3.0-beta-6-220 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/api/LuckPermsApi
	at org.dynmap.bukkit.permissions.LuckPermsPermissions.create(LuckPermsPermissions.java:26) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:848) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:475) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:299) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:878) ~[paperclip.jar:git-Purpur-322]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.api.LuckPermsApi
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[paperclip.jar:git-Purpur-322]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	... 11 more
[02:01:30] [Server thread/INFO]: [dynmap] Disabling dynmap v3.0-beta-6-220
[02:01:30] [Server thread/ERROR]: Error occurred while disabling dynmap v3.0-beta-6-220 (Is it up to date?)
java.lang.NullPointerException: null
	at org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:946) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:475) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:299) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:878) ~[paperclip.jar:git-Purpur-322]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

### PR DESCRIPTION
**Pull request by vijfhoek**
Updates LuckPerms to 5.0 and bStats to 1.5.

Fixes #2643, #2665 and #2669.

### CODE REVIEW

**Comment by vijfhoek** [comment]
I just realized part of my PR does the same as #2644. Fixing bStats was more of a side effect of updating LuckPerms, as an effort to get the darn thing to compile. No discredit intended, @MiniDigger

**Comment by MiniDigger** [comment]
Considering the PR is untouched for a month :shrug:

**Comment by vijfhoek** [comment]
Yeah it's kind of worrying that no PRs have been closed/merged since Jul 21

**Comment by ZandercraftGames** [comment]
People can compile from source... Just inconvenient

**Comment by BRGustavoRibeiro** [comment]
This needs to be merged! Good job 👍

**Comment by vijfhoek** [comment]
For what it's worth, I published [a release to my fork](https://github.com/SijmenSchoon/dynmap/releases/tag/v3.0-beta-7) so you can try/run it for yourself.

**Just to be completely clear, this is a beta release, and I am in no way, shape or form responsible for the loss of data or damage done to your server. I don't see a reason why, but...**
# MAKE A BACKUP

**Comment by Tsoccerguy3** [comment]
thank you

**Comment by mikeprimm** [comment]
This looks good - will sort out any overlap issues with the other PRs as I do further review and test.  Thanks!

**Comment by mikeprimm** [comment]
I'm going to need to roll this back - LuckPerms v5.0 is NOT the current released level (v4.4.1 is), and the code is incompatible with the released version, based on reports I'm getting.  The update has to support the released versions, and supporting a not-yet-released version is optional (if it needs to be a trade off choice) - as a policy, we never go the other way.

**Comment by mikeprimm** [comment]
OK - so, I've modified this so that we use the older LuckPerms code for the older versions, and the newer one for the newer versions.   Please give the latest dev build a look to confirm that things are working as you'd expect (I confirmed the plugin loaded properly and the like, but don't have a viable LuckPerms configuration for 4.4.1 vs 5.0.23 to feel really confident).

**Pull request merged**
