### PR TITLE
Updated Spigot / Bukkit builds for Minecraft 1.16.4

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by WouterGritter** [comment]
Can confirm that it works!

**Comment by tackleza** [comment]
Confirm this is working with 1.16.4 (Basic test)

**Comment by jjcf89** [comment]
I think i did something wrong, I tried building the branch and am getting the following error.

```
> Task :bukkit-helper-116-4:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':bukkit-helper-116-4:compileClasspath'.
> Could not find org.spigotmc:spigot:1.16.4-R0.1-SNAPSHOT.
  Searched in the following locations:
    - file:/home/jcormier/.m2/repository/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
    - file:/home/jcormier/.m2/repository/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
    - file:/home/jcormier/.m2/repository/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.jar
    - https://oss.sonatype.org/content/repositories/releases/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
    - https://oss.sonatype.org/content/repositories/releases/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
    - https://oss.sonatype.org/content/repositories/releases/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.jar
    - https://repo.mikeprimm.com/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
    - https://repo.mikeprimm.com/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
    - https://repo.mikeprimm.com/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.jar
    - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
    - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
    - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.jar
    - https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
    - https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
    - https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.jar
    - https://repo.codemc.org/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
    - https://repo.codemc.org/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
    - https://repo.codemc.org/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.jar
  Required by:
      project :bukkit-helper-116-4
```

**Comment by KairuByte** [comment]
This appears to add support for 1.16.4, but it also appears to potentially break support for 1.16.[0-3].

**Comment by tim-schneider** [comment]
@jjcf89 run spigots buildtools for 1.16.4 once and try again. You are just missing a local compiled copy of 1.16.4.

**Comment by ghost** [comment]
@jjcf89 Make sure to run builtools with the --rev 1.16.4 flag. I don't think 1.16.4 is flagged as 'latest' by the team at this moment.
@KairuByte I'll have a look.

**Comment by ghost** [comment]
I've changed the load order for the different Helper versions. This should prevent the contains("MC: 1.16") statement to cause newer server versions to load the wrong helper. This should fix the issue @KairuByte has. I did a quick test with spigot versions 1.16.1 through 1.16.4 and those seem fine so far.

**Comment by jjcf89** [comment]
> @jjcf89 Make sure to run builtools with the --rev 1.16.4 flag. I don't think 1.16.4 is flagged as 'latest' by the team at this moment.

Thanks
```
wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
java -jar BuildTools.jar --rev 1.16.4
```

**Comment by Tombstone1973** [comment]
Gives me an error about mismatched version on the webmap.

**Comment by FedUpWith-Tech** [comment]
Just to give everyone an update on this-

I don't have push access nor do I have the ability to upload compiled jars to the various distribution websites. I'm also not a java coder, all I do is slowly work on updating the wiki and help manage the dynmap discord. I know it seems like it is taking a really long time for the update to come out and I can't speak for mike but I know that there are a lot of other things going on in the world right now and updating a plugin isn't exactly priority #1. Sorry to keep everyone waiting and not bring good news but just like Nevada, I'm doing everything I can :P

Ninja edit: Aside from the other open PR's compiling this build as of commit 8ad0cff1b5d80ff34411fa73d840999555352193 will give a working 1.16.4 that does not contain malicious code. There is a version of dynmap floating around containing seriously altered code and I highly recommend compiling from this repo instead of downloading a compiled jar from a non-official source.

**Comment by jjcf89** [comment]
[Dynmap-3.1-1.16.4-test-SNAPSHOT-spigot.zip](https://github.com/webbukkit/dynmap/files/5505751/Dynmap-3.1-1.16.4-test-SNAPSHOT-spigot.zip)
Here is the copy I built, you need to extract the zip file

**Review by mikeprimm — APPROVED** [review]
Looks good - thanks for the PR!

**Pull request merged**
