### PR TITLE
update to 1.14.4 :) 

### PR DESCRIPTION
**Pull request by chbensch**

### CODE REVIEW

**Review by DamionDamion — APPROVED** [review]
Looks good to me.

**Comment by Prof-Bloodstone** [comment]
Keeping binaries in git isn't really a good idea. Other than that, looks good.

**Comment by chbensch** [comment]
> Keeping binaries in git isn't really a good idea. Other than that, looks good.

yeah sorry, I just wanted to make it available asap for the "normal" users.

**Review by DamionDamion — CHANGES_REQUESTED** [review]
> Looks good to me.

Unapproved due to binary in source tree

**Comment by Prof-Bloodstone** [comment]
> > Keeping binaries in git isn't really a good idea. Other than that, looks good.
> 
> yeah sorry, I just wanted to make it available asap for the "normal" users.

I imagine normal users won't search the git files, but could download a file if it's uploaded in the PR itself, or better yet in the issue (which I see you posted it in). Having it in the commit history means this PR probably shouldn't be merged until it's resolved, so it could be holding this PR from merging :)

**Pull request closed without merging**
