### PR TITLE
Fabric 1.16.4

### PR DESCRIPTION
**Pull request by lhns**
fixed ServerPlayNetworkHandlerMixin to make it work with fabric for minecraft 1.16.4

Crash for fabric-1.16.2 version on fabric-1.16.4 **without** this fix:
````
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.class_3321.method_14547(class_3321.java:64)
	at net.minecraft.class_3176.method_13951(class_3176.java:486)
	at net.minecraft.class_3176.method_3823(class_3176.java:162)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onGameMessage(Lnet/minecraft/class_2797;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/lang/String;)V in dynmap.mixins.json:ServerPlayNetworkHandlerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap dynmap-fabric-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 12 more
```

### CODE REVIEW

**Comment by DaggeSme** [comment]
Hello when trying to run dynmap in a fabric 1.16.4 docker container with lithium, phosphor and fabric api i get this error https://pastebin.com/PGwd7E81 Is the dynmap 1.16.4 fabric code wrong or is it on my end?

**Comment by lhns** [comment]
That is weird. I just built this and tried it on a fresh fabric 1.16.4 server with phosphor and lithium installed and the world loaded up just fine.
It seems like your jar might be missing the refmap file:
```Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on loadWorld could not find any targets matching 'loadWorld' in net.minecraft.server.MinecraftServer. No refMap loaded.```
I built the jar using the normal gradle build process and it contains a ```Dynmap-refmap.json``` with the following contents: https://gist.github.com/LolHens/8127d65f87cd63262f0a20828d9e9bea
Could you verify that your jar file also contains this file? Maybe you have to clean some gradle caches to fix this.

**Comment by Genau6502** [comment]
Just tested on my server, works fine with no obvious issues

**Comment by DaggeSme** [comment]
Sorry for late reply. The file was the same but I have some compiling errors I will try to compile on a different pc later today. In the error log it says to try a older version of gradle I have now tried gradle 6 and two different versions of gradle 4.

**Comment by lhns** [comment]
For everyone having problems compiling I made a small script you can run using docker that should get you reproducable builds. It will build the 1.16.4 jar file and move it into your current directory.
```sh
docker run -ti --rm -v "$(pwd):/host" openjdk:11 bash -c 'git clone https://github.com/LolHens/dynmap.git; cd dynmap; git checkout fabric-1.16.4; cat settings.gradle | grep -P "^$|[dD]ynmap|fabric-1\.16\.4" > settings.gradle.new; mv settings.gradle.new settings.gradle; ./gradlew build; mv target/* /host/.'
```

**Comment by ghost** [comment]
Hi!
I really want this on my server, but I'm having some trouble downloading it. Can someone help me? Or is there a simple guide. I just can't seem to find any download button. And what is this compiling you're talking about?

**Comment by JosephMillsAtWork** [comment]
Just want to say thanks I reviewed the code and also tested on fabric 1.16.4 Everything seems to be working for my needs. 
Thanks also for the script to help with easing the settings.gradle changes and saving me time with downloads ect.

**Review by mikeprimm — APPROVED** [review]

**Comment by mikeprimm** [comment]
Thanks!!

**Pull request merged**
