### PR TITLE
Fix missing api-version warning

### PR DESCRIPTION
**Pull request by TheDGOfficial**
As per comment from https://github.com/webbukkit/dynmap/issues/2536#issuecomment-521458380

### CODE REVIEW

**Review by Nicofisi — APPROVED** [review]
Yes, we need that

**Comment by mikeprimm** [comment]
Code technically supports versions older than 1.13 (and still has users using it) - need to confirm that this doesn't break those older versions.

**Comment by TheDGOfficial** [comment]
> Code technically supports versions older than 1.13 (and still has users using it) - need to confirm that this doesn't break those older versions.

It does not break since 1.12 and older versions do not have an "api-version" thing and they don't recognize the "api-version" setting in the plugin.yml. Bukkit just ignores unrecognized settings in the plugin.yml.

**Comment by mikeprimm** [comment]
Sounds good enough for me - thanks for the verification!

**Pull request merged**
