### PR TITLE
Backward port to Fabric 1.15.2 (from Fabric 1.16.1)

### PR DESCRIPTION
**Pull request by keuin**
Backward port to Fabric 1.15.2 (based on Fabric 1.16.1 codes).
I've tested on my server that it runs smoothly on MC 1.15.2.

### CODE REVIEW

**Review by mikeprimm — APPROVED** [review]

**Comment by mikeprimm** [comment]
Looks good - let's give it a try!

**Comment by mikeprimm** [comment]
Here's a development build of the integrated PR - please give it a try when you get a chance (I'm not set up for Fabric 1.15.2 just yet).   https://dynmap.us/builds/dynmap/Dynmap-3.1-SNAPSHOT-fabric-1.15.2.jar

**Comment by keuin** [comment]
> Here's a development build of the integrated PR - please give it a try when you get a chance (I'm not set up for Fabric 1.15.2 just yet). https://dynmap.us/builds/dynmap/Dynmap-3.1-SNAPSHOT-fabric-1.15.2.jar

OK, I will test it on my survival server. I've just installed the .jar you've post and it seems to work fine. In fact, I have been using the version I built myself for about a month, and no bugs were observed. Now I will try out this version.

**Comment by mikeprimm-triva** [comment]
Thanks for that!

**Pull request merged**
